version: "3.8"

services:
  database:
      image: postgres
      container_name: database_beeheroes
      restart: always
      ports: 
        - 55023:5432
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=eDu7Z8BBBXf
        - POSTGRES_DB=beeheroes
      volumes:
        - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: beeheroes
  #   restart: always
  #   ports: 
  #     - 3333:3333
  #     - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
  #   volumes: 
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database


volumes:
  pgdata:
    driver: local